name: Build configuration matrix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v2
    - working-directory: ${{github.workspace}}/tests/buildconfig

    - name: Default build
      run: bash ci.sh

    - name: Emulator debug build
      run: bash ci.sh -DRISCV_DEBUG=ON

    - name: Instruction cache build
      run: bash ci.sh -DRISCV_ICACHE=ON

    - name: No extensions build
      run: bash ci.sh -DRISCV_EXT_A=OFF -DRISCV_EXT_C=OFF -DRISCV_EXT_F=OFF

    - name: A-ext only build
      run: bash ci.sh -DRISCV_EXT_A=ON -DRISCV_EXT_C=OFF -DRISCV_EXT_F=OFF

    - name: C-ext only build
      run: bash ci.sh -DRISCV_EXT_A=OFF -DRISCV_EXT_C=ON -DRISCV_EXT_F=OFF

    - name: F-ext only build
      run: bash ci.sh -DRISCV_EXT_A=OFF -DRISCV_EXT_C=OFF -DRISCV_EXT_F=ON

    - name: Experimental build
      run: bash ci.sh -DRISCV_EXPERIMENTAL=ON -DRISCV_ICACHE=OFF

    - name: Experimental icache build
      run: bash ci.sh -DRISCV_EXPERIMENTAL=ON -DRISCV_ICACHE=ON

    - name: Experimental icache debug build
      run: bash ci.sh -DRISCV_EXPERIMENTAL=ON -DRISCV_ICACHE=ON -DRISCV_DEBUG=ON

    - name: No multiprocessing build
      run: bash ci.sh -DRISCV_MULTIPROCESS=OFF

    - name: Multiprocessing debug build
      run: bash ci.sh -DRISCV_MULTIPROCESS=ON -DRISCV_DEBUG=ON

